[platformio]
default_envs = solar_term

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/platformio_solaros_flavor.py

[env:solar_term]
board = solar_term
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=solar_term

[env:freenove_esp32_s3_display_4_0]
board = freenove_esp32_s3_display_4_0
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=freenove_esp32_s3_display_4_0

[env:ats_mini_v1]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=ats_mini_v1

[env:esp32_s3_devkitc1_n16r8]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=esp32_s3_devkitc1_n16r8

[env:cl_32]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=cl_32

[env:esp32_devkitc_v4_wrover]
board = freenove_esp32_wrover
board_build.partitions = partitions_4mb.csv
board_upload.maximum_size = 3997696
custom_solaros_default_flavor = rover
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=esp32_devkitc_v4_wrover -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.freenove_esp32_wrover_v3

[env:odroid_go]
board = odroid_esp32
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=odroid_go -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.odroid_go

[env:freenove_esp32_wrover_v3]
board = freenove_esp32_wrover
board_build.partitions = partitions_4mb.csv
board_upload.maximum_size = 3997696
custom_solaros_default_flavor = rover
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=freenove_esp32_wrover_v3 -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.freenove_esp32_wrover_v3

[env:elecrow_crowpanel_esp32_s3_4_2_epaper]
board = elecrow_crowpanel_esp32_s3_4_2_epaper
board_build.partitions = partitions_8mb.csv
custom_solaros_default_flavor = writerdeck
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=elecrow_crowpanel_esp32_s3_4_2_epaper -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.elecrow_crowpanel_esp32_s3_4_2_epaper

[env:ttgo_vga32_v14]
board = ttgo-t7-v14-mini32
board_build.partitions = partitions_4mb.csv
board_upload.maximum_size = 3997696
custom_solaros_default_flavor = vga32
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=ttgo_vga32_v14 -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.ttgo_vga32_v14
