[platformio]
default_envs = waveshare_esp32_s3_rlcd_4_2

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/platformio_solaros_flavor.py

[env:waveshare_esp32_s3_rlcd_4_2]
board = waveshare_esp32_s3_rlcd_4_2
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=waveshare_esp32_s3_rlcd_4_2

[env:esp32_s3_devkitc1_n16r8]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=esp32_s3_devkitc1_n16r8

[env:ats_mini_v1]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=ats_mini_v1

[env:odroid_go]
board = odroid_esp32
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=odroid_go -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.odroid_go

[env:m5stack_core2]
board = m5stack-core2
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=m5stack_core2 -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.m5stack_core2

[env:waveshare_esp32_s3_touch_lcd_5]
board = waveshare_esp32_s3_touch_lcd_5
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=waveshare_esp32_s3_touch_lcd_5 "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.waveshare_esp32_s3_touch_lcd_5"

[env:m5stack_cores3]
board = m5stack-cores3
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=m5stack_cores3 "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.m5stack_cores3"

[env:elecrow_crowpanel_esp32_s3_4_2_epaper]
board = elecrow_crowpanel_esp32_s3_4_2_epaper
board_build.partitions = partitions_8mb.csv
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=elecrow_crowpanel_esp32_s3_4_2_epaper -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.elecrow_crowpanel_esp32_s3_4_2_epaper
