#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "solar_os_board.h"

typedef uint64_t solar_os_board_capabilities_t;
typedef uint64_t solar_os_board_capability_t;

#define SOLAR_OS_BOARD_CAP_DISPLAY (1ULL << 0)
#define SOLAR_OS_BOARD_CAP_GFX (1ULL << 1)
#define SOLAR_OS_BOARD_CAP_CDC (1ULL << 2)
#define SOLAR_OS_BOARD_CAP_UART (1ULL << 3)
#define SOLAR_OS_BOARD_CAP_SD (1ULL << 4)
#define SOLAR_OS_BOARD_CAP_I2C (1ULL << 5)
#define SOLAR_OS_BOARD_CAP_RTC (1ULL << 6)
#define SOLAR_OS_BOARD_CAP_BATTERY (1ULL << 7)
#define SOLAR_OS_BOARD_CAP_AUDIO (1ULL << 8)
#define SOLAR_OS_BOARD_CAP_WIFI (1ULL << 9)
#define SOLAR_OS_BOARD_CAP_BLE (1ULL << 10)
#define SOLAR_OS_BOARD_CAP_GPIO (1ULL << 11)
#define SOLAR_OS_BOARD_CAP_ADC (1ULL << 12)
#define SOLAR_OS_BOARD_CAP_PWM (1ULL << 13)
#define SOLAR_OS_BOARD_CAP_KEY (1ULL << 14)
#define SOLAR_OS_BOARD_CAP_TEMPERATURE (1ULL << 15)
#define SOLAR_OS_BOARD_CAP_HUMIDITY (1ULL << 16)
#define SOLAR_OS_BOARD_CAP_PSRAM (1ULL << 17)
#define SOLAR_OS_BOARD_CAP_BUTTONS (1ULL << 18)
#define SOLAR_OS_BOARD_CAP_JOYSTICK (1ULL << 19)
#define SOLAR_OS_BOARD_CAP_ADC_DPAD (1ULL << 20)
#define SOLAR_OS_BOARD_CAP_SPI (1ULL << 21)
#define SOLAR_OS_BOARD_CAP_STATUS_LED (1ULL << 22)
#define SOLAR_OS_BOARD_CAP_DISPLAY_BRIGHTNESS (1ULL << 23)
#define SOLAR_OS_BOARD_CAP_AUDIO_INPUT (1ULL << 24)
#define SOLAR_OS_BOARD_CAP_EXPANSION_GPIO (1ULL << 25)
#define SOLAR_OS_BOARD_CAP_EXPANSION_I2C (1ULL << 26)
#define SOLAR_OS_BOARD_CAP_EXPANSION_SPI (1ULL << 27)
#define SOLAR_OS_BOARD_CAP_EXPANSION_UART (1ULL << 28)
#define SOLAR_OS_BOARD_CAP_EXPANSION_ADC (1ULL << 29)
#define SOLAR_OS_BOARD_CAP_EXPANSION_PWM (1ULL << 30)
#define SOLAR_OS_BOARD_CAP_SIMD (1ULL << 31)
#define SOLAR_OS_BOARD_CAP_CARDKB (1ULL << 32)
#define SOLAR_OS_BOARD_CAP_PM_UART (1ULL << 33)
#define SOLAR_OS_BOARD_CAP_PORT_A_I2C (1ULL << 34)
#define SOLAR_OS_BOARD_CAP_TOUCH (1ULL << 35)

#ifndef SOLAR_OS_BOARD_HAS_PSRAM
#define SOLAR_OS_BOARD_HAS_PSRAM 0
#endif
#ifndef SOLAR_OS_BOARD_PSRAM_BYTES
#define SOLAR_OS_BOARD_PSRAM_BYTES 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_DISPLAY
#define SOLAR_OS_BOARD_HAS_DISPLAY 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_GFX
#define SOLAR_OS_BOARD_HAS_GFX 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_CDC
#define SOLAR_OS_BOARD_HAS_CDC 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_UART
#define SOLAR_OS_BOARD_HAS_UART 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_SD
#define SOLAR_OS_BOARD_HAS_SD 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_I2C
#define SOLAR_OS_BOARD_HAS_I2C 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_SPI
#define SOLAR_OS_BOARD_HAS_SPI 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_RTC
#define SOLAR_OS_BOARD_HAS_RTC 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_BATTERY
#define SOLAR_OS_BOARD_HAS_BATTERY 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_AUDIO
#define SOLAR_OS_BOARD_HAS_AUDIO 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_AUDIO_INPUT
#define SOLAR_OS_BOARD_HAS_AUDIO_INPUT 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_WIFI
#define SOLAR_OS_BOARD_HAS_WIFI 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_BLE
#define SOLAR_OS_BOARD_HAS_BLE 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_GPIO
#define SOLAR_OS_BOARD_HAS_GPIO 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_ADC
#define SOLAR_OS_BOARD_HAS_ADC 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_PWM
#define SOLAR_OS_BOARD_HAS_PWM 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_GPIO
#define SOLAR_OS_BOARD_HAS_EXPANSION_GPIO 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_I2C
#define SOLAR_OS_BOARD_HAS_EXPANSION_I2C 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_SPI
#define SOLAR_OS_BOARD_HAS_EXPANSION_SPI 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_UART
#define SOLAR_OS_BOARD_HAS_EXPANSION_UART 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_ADC
#define SOLAR_OS_BOARD_HAS_EXPANSION_ADC 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_EXPANSION_PWM
#define SOLAR_OS_BOARD_HAS_EXPANSION_PWM 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_KEY
#define SOLAR_OS_BOARD_HAS_KEY 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_BUTTONS
#define SOLAR_OS_BOARD_HAS_BUTTONS 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_JOYSTICK
#define SOLAR_OS_BOARD_HAS_JOYSTICK 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_ADC_DPAD
#define SOLAR_OS_BOARD_HAS_ADC_DPAD 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_CARDKB
#define SOLAR_OS_BOARD_HAS_CARDKB 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_PM_UART
#define SOLAR_OS_BOARD_HAS_PM_UART 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_PORT_A_I2C
#define SOLAR_OS_BOARD_HAS_PORT_A_I2C 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_TOUCH
#define SOLAR_OS_BOARD_HAS_TOUCH 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_TEMPERATURE
#define SOLAR_OS_BOARD_HAS_TEMPERATURE 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_HUMIDITY
#define SOLAR_OS_BOARD_HAS_HUMIDITY 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_STATUS_LED
#define SOLAR_OS_BOARD_HAS_STATUS_LED 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_DISPLAY_BRIGHTNESS
#define SOLAR_OS_BOARD_HAS_DISPLAY_BRIGHTNESS 0
#endif
#ifndef SOLAR_OS_BOARD_HAS_SIMD
#define SOLAR_OS_BOARD_HAS_SIMD 0
#endif

solar_os_board_capabilities_t solar_os_board_capabilities(void);
bool solar_os_board_has(solar_os_board_capability_t capability);
const char *solar_os_board_capability_name(solar_os_board_capability_t capability);
void solar_os_board_capabilities_format(char *buffer, size_t buffer_len);
