[flavor]
name = "netrunner"
description = "Minimal SolarOS build with hardware services, and network tools."

[packages]
system = true
expansions = true
maintenance_apps = true
maintenance_jobs = true
audio = false
net = true
media = false
games = false
python = false
lua = false
utils = false
